services:
  - type: web
    name: api-registro-pacientes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: APP_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: MEDICO_PASSWORD
        generateValue: true
      - key: ENFERMERO_PASSWORD
        generateValue: true
